# === SonarCloud basic configuration ===
sonar.organization=sebastiangallegoc
sonar.projectKey=SebastianGallegoC_cypress-realworld-app
sonar.host.url=https://sonarcloud.io

# Rutas de código fuente a analizar (ajusta si es necesario)
sonar.sources=src,backend
sonar.tests=cypress,src,backend

# Excluir archivos de configuración y node_modules
sonar.exclusions=node_modules/**,**/*.config.js,**/*.config.ts

# Opcional: exclusiones de tests si hace falta
# sonar.test.exclusions=**/*.spec.ts,**/*.test.ts
